# Generated by Django 3.1.7 on 2021-03-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='asdasd', max_length=50),
            preserve_default=False,
        ),
    ]
