# Generated by Django 3.1.7 on 2021-04-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='suma', max_length=50),
            preserve_default=False,
        ),
    ]
