# Generated by Django 3.1.7 on 2021-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_volume',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
