# Generated by Django 2.2 on 2021-04-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stock_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_volume',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='uploads/images/'),
        ),
    ]
