# Generated by Django 3.1.7 on 2021-03-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceId', models.CharField(max_length=50)),
                ('customerName', models.CharField(max_length=50)),
                ('customerEmail', models.EmailField(max_length=254)),
                ('productCode', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=50)),
                ('productSize', models.CharField(max_length=50)),
                ('productPrice', models.PositiveIntegerField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('occasionDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('returnTime', models.TimeField()),
                ('rentalChoice', models.CharField(max_length=50)),
                ('advanceAmount', models.PositiveIntegerField()),
                ('rentalAmount', models.PositiveIntegerField()),
                ('refundAmount', models.PositiveIntegerField()),
                ('maintenanceAmount', models.PositiveIntegerField()),
                ('billingAmount', models.PositiveIntegerField()),
                ('paidAmount', models.PositiveIntegerField()),
            ],
        ),
    ]
