# Generated by Django 3.1 on 2021-04-13 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20210330_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiceDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
