# Generated by Django 3.1.7 on 2021-04-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_invoicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='occasionDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='returnDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='returnTime',
            field=models.CharField(max_length=50),
        ),
    ]
