# Generated by Django 3.1.7 on 2021-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20210414_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='rentalChoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='imageLink',
            field=models.CharField(default='broken.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
